name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          node-version: 18 # Specify your Node.js version
          package-manager: npm # Explicitly use npm

      - name: Verify build output
        run: ls -R dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        continue-on-error: true

      - name: Check deployment status
        if: ${{ steps.deployment.outcome != 'success' }}
        run: echo "Deployment failed! Check the logs for errors."